import { useState } from 'react'
import { Button } from '@leafygreen-ui/button'
import { Badge } from '@leafygreen-ui/badge'
import { Card } from '@leafygreen-ui/card'
import { H1, H2, H3, Body, Overline } from '@leafygreen-ui/typography'
import { Stepper, Step } from '@leafygreen-ui/stepper'
import { palette } from '../tokens'

// ─── Pipeline data ────────────────────────────────────────────────────────────

const MAIN_PATH = [
  { id: 'draft',    label: 'Draft Created',  desc: 'Package configured and drafts generated by Ghostwriter.', color: palette.gray.dark1,  bg: palette.gray.light2,  border: palette.gray.light1 },
  { id: 'review',   label: 'In Review',      desc: 'Submitted to a content reviewer for quality and accuracy check.', color: '#92400E', bg: '#FEF3C7', border: '#FCD34D' },
  { id: 'approved', label: 'Approved',       desc: 'Reviewer signs off — drafts are ready to share with your audience.', color: palette.green.dark2, bg: palette.green.light3, border: palette.green.dark1 },
]

const BRANCH_PATHS = [
  {
    id: 'changes',
    label: 'Changes Requested',
    desc: 'Reviewer sends the draft back with specific feedback. You edit and resubmit.',
    color: palette.blue.dark1,
    bg: palette.blue.light3,
    border: palette.blue.base,
    note: 'Returns to In Review after edits',
  },
  {
    id: 'denied',
    label: 'Denied',
    desc: 'Draft does not meet content standards and cannot be resubmitted in its current form.',
    color: '#991B1B',
    bg: '#FEE2E2',
    border: '#FCA5A5',
    note: 'Package closed — start a new one',
  },
]

// ─── Walkthrough steps ────────────────────────────────────────────────────────

const STEPS = [
  {
    title: 'Name Package',
    desc: 'Start by giving your content package a clear name. This helps you and your reviewer track what you\'re working on.',
    illustration: <StepIllustration1 />,
  },
  {
    title: 'Configure',
    desc: 'Select your target audience, output formats (Blog Post, LinkedIn Thread, Email Sequence), and the tone that fits your campaign.',
    illustration: <StepIllustration2 />,
  },
  {
    title: 'Preview',
    desc: 'As you fill in the form, the right panel updates in real time — showing an opening paragraph tailored to your audience and tone.',
    illustration: <StepIllustration3 />,
  },
  {
    title: 'Generate',
    desc: 'When you\'re satisfied with the preview, click Generate Drafts. Ghostwriter produces polished drafts for every format you selected.',
    illustration: <StepIllustration4 />,
  },
  {
    title: 'Submit',
    desc: 'Review your drafts and click Submit for Review. A content reviewer will check and approve within 1–2 business days.',
    illustration: <StepIllustration5 />,
  },
]

// ─── How it works cards ───────────────────────────────────────────────────────

const HOW_IT_WORKS = [
  {
    icon: '✏️',
    title: 'Configure',
    desc: 'Set your campaign name, target audience, output formats, and tone. Ghostwriter adapts every draft to your exact specifications.',
  },
  {
    icon: '⚡',
    title: 'Preview & Generate',
    desc: 'A live preview updates as you type. When you\'re ready, generate full polished drafts for all selected formats at once.',
  },
  {
    icon: '✅',
    title: 'Review & Approve',
    desc: 'Every draft goes through a human review before it reaches your audience — ensuring quality, accuracy, and brand alignment.',
  },
]

// ─── LandingPage ─────────────────────────────────────────────────────────────

export function LandingPage({ onGetStarted }: { onGetStarted: () => void }) {
  const [showModal, setShowModal] = useState(false)
  const [step, setStep] = useState(0)

  const openModal = () => { setStep(0); setShowModal(true) }
  const closeModal = () => setShowModal(false)

  return (
    <>
      <style>{`
        @keyframes gw3-fade-in {
          from { opacity: 0; transform: translateY(12px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .gw3-animate { animation: gw3-fade-in 0.4s ease-out forwards; }
      `}</style>

      <div style={{ flex: 1, overflowY: 'auto', background: palette.white }}>

        {/* ── Hero ─────────────────────────────────────────────────────── */}
        <section style={{
          padding: '80px 32px 72px',
          display: 'flex', flexDirection: 'column', alignItems: 'center',
          textAlign: 'center', background: palette.white,
        }}>
          <div className="gw3-animate" style={{ marginBottom: 16 }}>
            <Badge variant="green">AI-powered · MongoDB</Badge>
          </div>
          <H1 className="gw3-animate" style={{ maxWidth: 640, marginBottom: 20, animationDelay: '0.05s' }}>
            Create polished content, every time.
          </H1>
          <Body className="gw3-animate" style={{
            maxWidth: 520, color: palette.gray.dark1, lineHeight: 1.75,
            marginBottom: 36, fontSize: 16, animationDelay: '0.1s',
          } as React.CSSProperties}>
            Configure your campaign brief, choose your formats, and let Ghostwriter produce
            review-ready drafts in minutes — with a structured human review built right in.
          </Body>
          <div className="gw3-animate" style={{ display: 'flex', gap: 12, animationDelay: '0.15s' }}>
            <Button variant="primary" onClick={onGetStarted}>
              Get started →
            </Button>
            <Button variant="default" onClick={openModal}>
              How it works
            </Button>
          </div>
        </section>

        {/* ── Pipeline ─────────────────────────────────────────────────── */}
        <section style={{
          padding: '64px 32px',
          background: palette.gray.light3,
          borderTop: `1px solid ${palette.gray.light2}`,
          borderBottom: `1px solid ${palette.gray.light2}`,
        }}>
          <div style={{ maxWidth: 880, margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: 48 }}>
              <Overline style={{ display: 'block', marginBottom: 10, color: palette.green.dark2 }}>
                CONTENT LIFECYCLE
              </Overline>
              <H2 style={{ marginBottom: 10 }}>From first draft to approved content</H2>
              <Body style={{ color: palette.gray.dark1, maxWidth: 480, margin: '0 auto' }}>
                Every package goes through a structured review process before it reaches your audience.
              </Body>
            </div>

            {/* Main path */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 0, marginBottom: 32, justifyContent: 'center' }}>
              {MAIN_PATH.map((stage, i) => (
                <div key={stage.id} style={{ display: 'flex', alignItems: 'center' }}>
                  <PipelineNode
                    label={stage.label}
                    desc={stage.desc}
                    color={stage.color}
                    bg={stage.bg}
                    border={stage.border}
                    checkmark={stage.id === 'approved'}
                  />
                  {i < MAIN_PATH.length - 1 && (
                    <div style={{ display: 'flex', alignItems: 'center', padding: '0 8px', flexShrink: 0, marginBottom: 32 }}>
                      <div style={{ width: 32, height: 2, background: palette.gray.light1 }} />
                      <div style={{
                        width: 0, height: 0,
                        borderTop: '5px solid transparent',
                        borderBottom: '5px solid transparent',
                        borderLeft: `6px solid ${palette.gray.light1}`,
                      }} />
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Branch separator */}
            <div style={{
              display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24,
            }}>
              <div style={{ flex: 1, height: 1, background: palette.gray.light2 }} />
              <Body style={{ fontSize: 11, color: palette.gray.dark1, fontWeight: 600, letterSpacing: '0.5px' } as React.CSSProperties}>
                POSSIBLE OUTCOMES FROM REVIEW
              </Body>
              <div style={{ flex: 1, height: 1, background: palette.gray.light2 }} />
            </div>

            {/* Branch paths */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
              {BRANCH_PATHS.map(branch => (
                <div key={branch.id} style={{
                  background: branch.bg,
                  border: `1px solid ${branch.border}`,
                  borderRadius: 10, padding: '18px 20px',
                  display: 'flex', gap: 14, alignItems: 'flex-start',
                }}>
                  <div style={{
                    width: 10, height: 10, borderRadius: '50%',
                    background: branch.border, flexShrink: 0, marginTop: 5,
                  }} />
                  <div>
                    <Body style={{ fontWeight: 600, color: branch.color, marginBottom: 4 } as React.CSSProperties}>
                      {branch.label}
                    </Body>
                    <Body style={{ fontSize: 12, color: palette.gray.dark1, marginBottom: 6, lineHeight: 1.55 } as React.CSSProperties}>
                      {branch.desc}
                    </Body>
                    <Body style={{ fontSize: 11, color: branch.color, fontStyle: 'italic' } as React.CSSProperties}>
                      {branch.note}
                    </Body>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── How it works ─────────────────────────────────────────────── */}
        <section style={{ padding: '64px 32px', background: palette.white }}>
          <div style={{ maxWidth: 880, margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: 40 }}>
              <Overline style={{ display: 'block', marginBottom: 10, color: palette.green.dark2 }}>
                HOW IT WORKS
              </Overline>
              <H2>Three steps to review-ready content</H2>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 }}>
              {HOW_IT_WORKS.map((item, i) => (
                <Card key={item.title} style={{ padding: '28px 24px' }}>
                  <div style={{
                    width: 40, height: 40, borderRadius: 10,
                    background: palette.green.light3,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: 20, marginBottom: 16,
                  }}>
                    {item.icon}
                  </div>
                  <div style={{
                    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                    width: 22, height: 22, borderRadius: '50%',
                    background: palette.green.dark1, color: palette.white,
                    fontSize: 11, fontWeight: 700, marginBottom: 10,
                    fontFamily: "'Euclid Circular A', sans-serif",
                  }}>
                    {i + 1}
                  </div>
                  <H3 style={{ marginBottom: 8 }}>{item.title}</H3>
                  <Body style={{ color: palette.gray.dark1, fontSize: 13, lineHeight: 1.65 } as React.CSSProperties}>
                    {item.desc}
                  </Body>
                </Card>
              ))}
            </div>
          </div>
        </section>


      </div>

      {/* ── Walkthrough Modal ─────────────────────────────────────────── */}
      {showModal && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 100,
          background: 'rgba(0,0,0,0.5)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          padding: 24,
        }}
          onClick={e => { if (e.target === e.currentTarget) closeModal() }}
        >
          <div style={{
            background: palette.white, borderRadius: 12,
            width: '100%', maxWidth: 640,
            display: 'flex', flexDirection: 'column',
            maxHeight: 'calc(100vh - 48px)', overflow: 'hidden',
            boxShadow: '0 20px 60px rgba(0,0,0,0.25)',
          }}>
            {/* Modal header */}
            <div style={{
              padding: '20px 24px', borderBottom: `1px solid ${palette.gray.light2}`,
              display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0,
            }}>
              <div style={{ flex: 1 }}>
                <Body style={{ fontWeight: 600, color: '#001E2B' } as React.CSSProperties}>
                  How to Use a Ghostwriter
                </Body>
              </div>
              <button
                onClick={closeModal}
                style={{
                  width: 32, height: 32, borderRadius: '50%',
                  background: palette.gray.light2, border: 'none', cursor: 'pointer',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 16, color: palette.gray.dark1, flexShrink: 0,
                }}
              >
                ×
              </button>
            </div>

            {/* LG Stepper */}
            <div style={{ padding: '16px 24px', borderBottom: `1px solid ${palette.gray.light2}`, flexShrink: 0 }}>
              {/* @ts-ignore */}
              <Stepper currentStep={step}>
                {STEPS.map(s => (
                  // @ts-ignore
                  <Step key={s.title}>{s.title}</Step>
                ))}
              </Stepper>
            </div>

            {/* Modal body */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '28px 24px' }}>
              {/* Illustration */}
              <div style={{
                background: palette.gray.light3, borderRadius: 10,
                border: `1px solid ${palette.gray.light2}`,
                marginBottom: 24, overflow: 'hidden',
              }}>
                {STEPS[step].illustration}
              </div>
              {/* Step description */}
              <Body style={{ color: palette.gray.dark1, lineHeight: 1.75, fontSize: 14 } as React.CSSProperties}>
                {STEPS[step].desc}
              </Body>
            </div>

            {/* Modal footer */}
            <div style={{
              padding: '16px 24px', borderTop: `1px solid ${palette.gray.light2}`,
              display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0,
            }}>
              <Button
                variant="default"
                disabled={step === 0}
                onClick={() => setStep(s => s - 1)}
              >
                ← Previous
              </Button>
              <div style={{ flex: 1 }} />
              {step < STEPS.length - 1 ? (
                <Button variant="primary" onClick={() => setStep(s => s + 1)}>
                  Next →
                </Button>
              ) : (
                <Button variant="primary" onClick={() => { closeModal(); onGetStarted() }}>
                  Get started →
                </Button>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  )
}

// ─── Pipeline node ────────────────────────────────────────────────────────────

function PipelineNode({ label, desc, color, bg, border, checkmark }: {
  label: string; desc: string; color: string; bg: string; border: string; checkmark?: boolean
}) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', width: 200, textAlign: 'center' }}>
      <div style={{
        padding: '10px 18px', borderRadius: 8,
        background: bg, border: `1.5px solid ${border}`,
        display: 'flex', alignItems: 'center', gap: 8,
        marginBottom: 10, whiteSpace: 'nowrap' as const,
      }}>
        {checkmark && (
          <div style={{
            width: 16, height: 16, borderRadius: '50%',
            background: border, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
          }}>
            <span style={{ color: palette.white, fontSize: 9, fontWeight: 700 }}>✓</span>
          </div>
        )}
        <span style={{
          fontSize: 13, fontWeight: 600, color,
          fontFamily: "'Euclid Circular A', sans-serif",
        }}>
          {label}
        </span>
      </div>
      <Body style={{ fontSize: 11, color: palette.gray.dark1, lineHeight: 1.5, maxWidth: 180 } as React.CSSProperties}>
        {desc}
      </Body>
    </div>
  )
}

// ─── Step illustrations ───────────────────────────────────────────────────────

function StepIllustration1() {
  return (
    <div style={{ padding: '28px 32px', display: 'flex', flexDirection: 'column', gap: 8 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: palette.gray.dark1, marginBottom: 4, fontFamily: 'inherit' }}>
        Campaign Name
      </div>
      <div style={{
        border: `2px solid ${palette.green.dark1}`, borderRadius: 6, padding: '10px 14px',
        background: palette.white, fontSize: 13, color: palette.black,
        fontFamily: "'Euclid Circular A', sans-serif",
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <span>AI Native Developer Campaign — Q2 2026</span>
        <div style={{ width: 2, height: 16, background: palette.green.dark1, animation: 'none' }} />
      </div>
      <div style={{ fontSize: 11, color: palette.gray.base, fontFamily: 'inherit' }}>
        e.g. Atlas Search Launch · Q3 2026
      </div>
    </div>
  )
}

function StepIllustration2() {
  const audiences = ['AI-Native Engineers', 'Developer (General)', 'Tech Executives', 'Social Media']
  const formats   = ['Blog Post', 'LinkedIn Thread', 'Email Sequence']
  return (
    <div style={{ padding: '20px 24px', display: 'flex', flexDirection: 'column', gap: 14 }}>
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: palette.gray.dark1, marginBottom: 6, fontFamily: 'inherit' }}>Audience</div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
          {audiences.map((a, i) => (
            <div key={a} style={{
              padding: '7px 10px', borderRadius: 6, fontSize: 11,
              border: `1px solid ${i === 0 ? palette.green.dark1 : palette.gray.light2}`,
              background: i === 0 ? palette.green.light3 : palette.white,
              color: i === 0 ? palette.green.dark2 : palette.gray.dark1,
              fontFamily: "'Euclid Circular A', sans-serif", fontWeight: i === 0 ? 600 : 400,
            }}>{a}</div>
          ))}
        </div>
      </div>
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: palette.gray.dark1, marginBottom: 6, fontFamily: 'inherit' }}>Output formats</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {formats.map((f, i) => (
            <div key={f} style={{
              display: 'flex', alignItems: 'center', gap: 8, padding: '6px 10px',
              borderRadius: 6, border: `1px solid ${i < 2 ? palette.green.dark1 : palette.gray.light2}`,
              background: i < 2 ? palette.green.light3 : palette.white,
            }}>
              <div style={{
                width: 14, height: 14, borderRadius: 3, flexShrink: 0,
                background: i < 2 ? palette.green.dark1 : 'transparent',
                border: `1.5px solid ${i < 2 ? palette.green.dark1 : palette.gray.light1}`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                {i < 2 && <span style={{ color: palette.white, fontSize: 8, fontWeight: 700 }}>✓</span>}
              </div>
              <span style={{ fontSize: 11, color: palette.black, fontFamily: "'Euclid Circular A', sans-serif" }}>{f}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

function StepIllustration3() {
  return (
    <div style={{ display: 'flex', height: 160 }}>
      {/* Left form panel */}
      <div style={{ width: 140, borderRight: `1px solid ${palette.gray.light2}`, padding: '14px 12px', flexShrink: 0 }}>
        {['Campaign Name', 'Audience', 'Format', 'Tone'].map(label => (
          <div key={label} style={{ marginBottom: 10 }}>
            <div style={{ fontSize: 10, fontWeight: 600, color: palette.gray.dark1, marginBottom: 3, fontFamily: 'inherit' }}>{label}</div>
            <div style={{ height: 8, borderRadius: 4, background: palette.gray.light2, width: label === 'Campaign Name' ? '90%' : '70%' }} />
          </div>
        ))}
      </div>
      {/* Right preview panel */}
      <div style={{ flex: 1, padding: '14px 16px', background: palette.gray.light3 }}>
        <div style={{ display: 'flex', gap: 6, marginBottom: 10 }}>
          <div style={{ padding: '2px 8px', borderRadius: 4, background: palette.green.light3, border: `1px solid ${palette.green.dark1}`, fontSize: 10, color: palette.green.dark2, fontFamily: 'inherit', fontWeight: 600 }}>Blog Post</div>
          <div style={{ padding: '2px 8px', borderRadius: 4, background: palette.gray.light2, fontSize: 10, color: palette.gray.dark1, fontFamily: 'inherit' }}>Live Preview</div>
        </div>
        <div style={{ fontSize: 11, color: palette.black, lineHeight: 1.55, marginBottom: 10, fontFamily: "'Euclid Circular A', sans-serif" }}>
          "When we started building our RAG pipeline at scale, the first thing we broke…"
        </div>
        {[80, 65, 75, 55].map((w, i) => (
          <div key={i} style={{ height: 7, borderRadius: 3, background: palette.gray.light2, width: `${w}%`, marginBottom: 5 }} />
        ))}
      </div>
    </div>
  )
}

function StepIllustration4() {
  const items = [
    { label: 'Blog Post',       done: true  },
    { label: 'LinkedIn Thread', done: true  },
    { label: 'Email Sequence',  done: false },
  ]
  return (
    <div style={{ padding: '24px 32px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
        <div style={{ padding: '3px 10px', borderRadius: 4, background: '#FEF3C7', border: '1px solid #FCD34D', fontSize: 11, fontWeight: 600, color: '#92400E', fontFamily: 'inherit' }}>
          Generating
        </div>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 16 }}>
        {items.map(item => (
          <div key={item.label} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{
              width: 16, height: 16, borderRadius: '50%', flexShrink: 0,
              background: item.done ? palette.green.dark1 : palette.gray.light2,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              {item.done && <span style={{ color: palette.white, fontSize: 8, fontWeight: 700 }}>✓</span>}
            </div>
            <span style={{ fontSize: 12, color: item.done ? palette.black : palette.gray.dark1, fontFamily: "'Euclid Circular A', sans-serif" }}>
              {item.label}
            </span>
          </div>
        ))}
      </div>
      <div style={{ height: 6, borderRadius: 3, background: palette.gray.light2, overflow: 'hidden' }}>
        <div style={{ height: '100%', borderRadius: 3, background: palette.green.dark1, width: '66%' }} />
      </div>
    </div>
  )
}

function StepIllustration5() {
  return (
    <div style={{ padding: '20px 24px' }}>
      <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 12 }}>
        <div style={{ padding: '3px 10px', borderRadius: 4, background: palette.green.light3, border: `1px solid ${palette.green.dark1}`, fontSize: 11, fontWeight: 600, color: palette.green.dark2, fontFamily: 'inherit' }}>Blog Post</div>
        <div style={{ padding: '3px 10px', borderRadius: 4, background: palette.green.light3, border: `1px solid ${palette.green.dark1}`, fontSize: 11, fontWeight: 600, color: palette.green.dark2, fontFamily: 'inherit' }}>Ready for review</div>
      </div>
      <div style={{ fontSize: 12, color: palette.black, lineHeight: 1.6, marginBottom: 14, fontFamily: "'Euclid Circular A', sans-serif" }}>
        Building Production RAG: What We Got Wrong (And How to Fix It)
      </div>
      {[90, 75, 82, 60].map((w, i) => (
        <div key={i} style={{ height: 7, borderRadius: 3, background: palette.gray.light2, width: `${w}%`, marginBottom: 5 }} />
      ))}
      <div style={{
        marginTop: 14, paddingTop: 12, borderTop: `1px solid ${palette.gray.light2}`,
        display: 'flex', gap: 8,
      }}>
        <div style={{ padding: '6px 14px', borderRadius: 5, border: `1px solid ${palette.gray.light2}`, fontSize: 11, color: palette.gray.dark1, fontFamily: 'inherit' }}>Download draft</div>
        <div style={{ padding: '6px 14px', borderRadius: 5, background: palette.green.dark1, fontSize: 11, color: palette.white, fontWeight: 600, fontFamily: 'inherit' }}>Submit for Review →</div>
      </div>
    </div>
  )
}
