import { useState } from 'react'
import { Button } from '@leafygreen-ui/button'
import IconButton from '@leafygreen-ui/icon-button'
import { Card } from '@leafygreen-ui/card'
import { H1, H2, H3, Body, Overline, Label } from '@leafygreen-ui/typography'
import { Stepper, Step } from '@leafygreen-ui/stepper'
import Icon from '@leafygreen-ui/icon'
import { palette } from '../tokens'

// ─── Pipeline data ────────────────────────────────────────────────────────────

const MAIN_PATH = [
  { id: 'draft',  label: 'Draft Created', desc: 'Package configured and drafts generated by Ghostwriter.', color: palette.gray.dark1, bg: palette.gray.light2, border: palette.gray.light1 },
  { id: 'review', label: 'In Review',     desc: 'Downloaded and submitted externally. Marked for review in Ghostwriter while you await a decision.', color: '#92400E', bg: '#FEF3C7', border: '#FCD34D' },
]

const OUTCOMES = [
  {
    id: 'approved',
    label: 'Approved',
    desc: 'Reviewer decision recorded — drafts are ready to share with your audience.',
    color: palette.green.dark2,
    bg: palette.green.light3,
    border: palette.green.dark1,
    checkmark: true,
  },
  {
    id: 'denied',
    label: 'Try Again',
    desc: 'Draft does not meet content standards. Record the denial reason in Package History for your reference.',
    color: '#991B1B',
    bg: '#FEE2E2',
    border: '#FCA5A5',
    checkmark: false,
  },
]

// ─── Walkthrough steps ────────────────────────────────────────────────────────

const STEPS = [
  {
    title: 'Name Package',
    desc: 'Start by giving your content package a clear name. This is how you and your reviewer will identify it throughout the process.',
    illustration: <StepIllustration1 />,
  },
  {
    title: 'Write Your Prompt',
    desc: 'Describe what you\'d like Ghostwriter to create in the Prompt field. You can also attach supporting files — briefs, outlines, or reference docs — for additional context.',
    illustration: <StepIllustration2 />,
  },
  {
    title: 'Preview & Generate',
    desc: 'The right panel shows a live preview as you type your package name. When you\'re ready, click Generate Drafts and Ghostwriter produces your content.',
    illustration: <StepIllustration3 />,
  },
  {
    title: 'Download for Review',
    desc: 'Once your drafts are ready, click "Download for Review" to export them as a PDF. This marks the draft as ready to share with your external reviewer.',
    illustration: <StepIllustration5 />,
  },
  {
    title: 'Mark for Review',
    desc: 'Click "Mark for Review" to log the package as in review inside Ghostwriter. Then submit the PDF to your reviewer outside the tool and await their response.',
    illustration: <StepIllustration4 />,
  },
  {
    title: 'Record Decision',
    desc: 'When your reviewer responds, return to Package History and find the package. Record their decision — approved or denied. The package status updates immediately.',
    illustration: <StepIllustrationRecord />,
  },
]

// ─── How it works cards ───────────────────────────────────────────────────────

const HOW_IT_WORKS = [
  {
    glyph: 'Edit',
    title: 'Write Your Prompt & Generate',
    desc: 'Name your package and write a prompt describing what to create. Attach supporting files if needed, then click Generate Drafts.',
  },
  {
    glyph: 'Download',
    title: 'Download for Review',
    desc: 'Download your drafts as a PDF and click "Mark for Review" to log the package. Submit the PDF to your reviewer outside Ghostwriter.',
  },
  {
    glyph: 'CheckmarkWithCircle',
    title: 'Record the Decision',
    desc: 'Once your reviewer responds, return to Package History to record the outcome. Packages are marked approved or denied — no changes requested.',
  },
]

// ─── LandingPage ─────────────────────────────────────────────────────────────

export function LandingPage({ onGetStarted }: { onGetStarted: () => void }) {
  const [showModal, setShowModal] = useState(false)
  const [step, setStep] = useState(0)

  const openModal = () => { setStep(0); setShowModal(true) }
  const closeModal = () => setShowModal(false)

  return (
    <>
      <style>{`
        @keyframes gw3-fade-in {
          from { opacity: 0; transform: translateY(12px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .gw3-animate { animation: gw3-fade-in 0.4s ease-out forwards; }
      `}</style>

      <div style={{ flex: 1, overflowY: 'auto', background: palette.white }}>

        {/* ── Hero ─────────────────────────────────────────────────────── */}
        <section style={{
          padding: '80px 32px 72px',
          display: 'flex', flexDirection: 'column', alignItems: 'center',
          textAlign: 'center', background: palette.white,
        }}>
          <div className="gw3-animate" style={{ marginBottom: 16 }}>
            <Overline style={{ color: '#00684A' }}>AI-powered · MongoDB</Overline>
          </div>
          <H1 className="gw3-animate" style={{ maxWidth: 640, marginBottom: 20, animationDelay: '0.05s' }}>
            Create polished content, every time.
          </H1>
          <Body className="gw3-animate" style={{
            maxWidth: 520, color: palette.gray.dark1, lineHeight: 1.75,
            marginBottom: 36, fontSize: 16, animationDelay: '0.1s',
          } as React.CSSProperties}>
            Name your package, write a prompt, and let Ghostwriter produce
            polished drafts in minutes. Download, submit for external review, then return to record the outcome.
          </Body>
          <div className="gw3-animate" style={{ display: 'flex', gap: 12, animationDelay: '0.15s' }}>
            <Button variant="primary" onClick={onGetStarted}>
              Get started
            </Button>
            <Button variant="default" onClick={openModal}>
              How it works
            </Button>
          </div>
        </section>

        {/* ── Pipeline ─────────────────────────────────────────────────── */}
        <section style={{
          padding: '64px 32px',
          background: palette.gray.light3,
          borderTop: `1px solid ${palette.gray.light2}`,
          borderBottom: `1px solid ${palette.gray.light2}`,
        }}>
          <div style={{ maxWidth: 880, margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: 48 }}>
              <Overline style={{ display: 'block', marginBottom: 10, color: palette.green.dark2 }}>
                CONTENT LIFECYCLE
              </Overline>
              <H2 style={{ marginBottom: 10 }}>From first draft to approved content</H2>
              <Body style={{ color: palette.gray.dark1, maxWidth: 480, margin: '0 auto' }}>
                Every package goes through a structured review process before it reaches your audience.
              </Body>
            </div>

            {/* Pipeline: Draft → In Review → Approved / Denied */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 32 }}>

              <PipelineNode
                label={MAIN_PATH[0].label} desc={MAIN_PATH[0].desc}
                color={MAIN_PATH[0].color} bg={MAIN_PATH[0].bg}
                border={MAIN_PATH[0].border} checkmark={false}
              />

              {/* Arrow */}
              <div style={{ display: 'flex', alignItems: 'center', padding: '0 8px', flexShrink: 0, marginBottom: 32 }}>
                <div style={{ width: 32, height: 2, background: palette.gray.light1 }} />
                <div style={{ width: 0, height: 0, borderTop: '5px solid transparent', borderBottom: '5px solid transparent', borderLeft: `6px solid ${palette.gray.light1}` }} />
              </div>

              <PipelineNode
                label={MAIN_PATH[1].label} desc={MAIN_PATH[1].desc}
                color={MAIN_PATH[1].color} bg={MAIN_PATH[1].bg}
                border={MAIN_PATH[1].border} checkmark={false}
              />

              {/* Angled fork arrows + outcomes */}
              <div style={{ display: 'flex', alignItems: 'center', flexShrink: 0 }}>
                <svg width="72" height="220" style={{ flexShrink: 0 }}>
                  <defs>
                    {/* markerUnits="userSpaceOnUse" makes dimensions literal px, not scaled by strokeWidth */}
                    <marker id="fork-arrow" markerWidth="6" markerHeight="10" refX="6" refY="5" orient="auto" markerUnits="userSpaceOnUse">
                      <polygon points="0 0, 6 5, 0 10" fill={palette.gray.light1} />
                    </marker>
                  </defs>
                  {/* Approved — angles upward */}
                  <line x1="4" y1="110" x2="64" y2="40" stroke={palette.gray.light1} strokeWidth="2" markerEnd="url(#fork-arrow)" />
                  {/* Denied — angles downward */}
                  <line x1="4" y1="110" x2="64" y2="180" stroke={palette.gray.light1} strokeWidth="2" markerEnd="url(#fork-arrow)" />
                </svg>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
                  {OUTCOMES.map(o => (
                    <PipelineNode
                      key={o.id}
                      label={o.label} desc={o.desc}
                      color={o.color} bg={o.bg}
                      border={o.border} checkmark={o.checkmark}
                    />
                  ))}
                </div>
              </div>

            </div>
          </div>
        </section>

        {/* ── How it works ─────────────────────────────────────────────── */}
        <section style={{ padding: '64px 32px', background: palette.white }}>
          <div style={{ maxWidth: 880, margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: 40 }}>
              <Overline style={{ display: 'block', marginBottom: 10, color: palette.green.dark2 }}>
                HOW IT WORKS
              </Overline>
              <H2>Three steps to review-ready content</H2>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 }}>
              {HOW_IT_WORKS.map((item, i) => (
                <Card key={item.title} style={{ padding: '28px 24px' }}>
                  <div style={{
                    width: 40, height: 40, borderRadius: 10,
                    background: palette.green.light3,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    marginBottom: 16,
                  }}>
                    <Icon glyph={item.glyph} fill={palette.green.dark2} size={20} />
                  </div>
                  <div style={{
                    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                    width: 22, height: 22, borderRadius: '50%',
                    background: palette.green.dark2,
                    marginBottom: 10,
                  }}>
                    <Label style={{ color: palette.white, margin: 0, lineHeight: 1 } as React.CSSProperties}>
                      {i + 1}
                    </Label>
                  </div>
                  <H3 style={{ marginBottom: 8 }}>{item.title}</H3>
                  <Body style={{ color: palette.gray.dark1, fontSize: 13, lineHeight: 1.65 } as React.CSSProperties}>
                    {item.desc}
                  </Body>
                </Card>
              ))}
            </div>
          </div>
        </section>


      </div>

      {/* ── Walkthrough Modal ─────────────────────────────────────────── */}
      {showModal && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 100,
          background: 'rgba(0,0,0,0.5)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          padding: 24,
        }}
          onClick={e => { if (e.target === e.currentTarget) closeModal() }}
        >
          <div style={{
            background: palette.white, borderRadius: 12,
            width: '100%', maxWidth: 640,
            display: 'flex', flexDirection: 'column',
            maxHeight: 'calc(100vh - 48px)', overflow: 'hidden',
            boxShadow: '0 20px 60px rgba(0,0,0,0.25)',
          }}>
            {/* Modal header */}
            <div style={{
              padding: '20px 24px', borderBottom: `1px solid ${palette.gray.light2}`,
              display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0,
            }}>
              <div style={{ flex: 1 }}>
                <Body style={{ fontWeight: 600, color: '#001E2B' } as React.CSSProperties}>
                  How to Use a Ghostwriter
                </Body>
              </div>
              {/* @ts-ignore */}
              <IconButton aria-label="Close" onClick={closeModal}>
                <Icon glyph="X" />
              </IconButton>
            </div>

            {/* LG Stepper */}
            <div style={{ padding: '16px 24px', borderBottom: `1px solid ${palette.gray.light2}`, flexShrink: 0 }}>
              {/* @ts-ignore */}
              <Stepper currentStep={step}>
                {/* @ts-ignore */}
                <Step>Name Package</Step>
                {/* @ts-ignore */}
                <Step>Prompt</Step>
                {/* @ts-ignore */}
                <Step>Generate</Step>
                {/* @ts-ignore */}
                <Step>Download</Step>
                {/* @ts-ignore */}
                <Step>Mark</Step>
                {/* @ts-ignore */}
                <Step>Record</Step>
              </Stepper>
            </div>

            {/* Modal body */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '28px 24px' }}>
              {/* Illustration */}
              <div style={{
                background: palette.gray.light3, borderRadius: 10,
                border: `1px solid ${palette.gray.light2}`,
                marginBottom: 24, overflow: 'hidden',
              }}>
                {STEPS[step].illustration}
              </div>
              {/* Step description */}
              <Body style={{ color: palette.gray.dark1, lineHeight: 1.75, fontSize: 14 } as React.CSSProperties}>
                {STEPS[step].desc}
              </Body>
            </div>

            {/* Modal footer */}
            <div style={{
              padding: '16px 24px', borderTop: `1px solid ${palette.gray.light2}`,
              display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0,
            }}>
              <Button
                variant="default"
                disabled={step === 0}
                onClick={() => setStep(s => s - 1)}
              >
                ← Previous
              </Button>
              <div style={{ flex: 1 }} />
              {step < STEPS.length - 1 ? (
                <Button variant="primary" onClick={() => setStep(s => s + 1)}>
                  Next →
                </Button>
              ) : (
                <Button variant="primary" onClick={() => { closeModal(); onGetStarted() }}>
                  Get started →
                </Button>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  )
}

// ─── Pipeline node ────────────────────────────────────────────────────────────

function PipelineNode({ label, desc, color, bg, border, checkmark }: {
  label: string; desc: string; color: string; bg: string; border: string; checkmark?: boolean
}) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', width: 200, textAlign: 'center' }}>
      <div style={{
        padding: '10px 18px', borderRadius: 8,
        background: bg, border: `1.5px solid ${border}`,
        display: 'flex', alignItems: 'center', gap: 8,
        marginBottom: 10, whiteSpace: 'nowrap' as const,
      }}>
        {checkmark && (
          <div style={{
            width: 16, height: 16, borderRadius: '50%',
            background: border, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
          }}>
            <span style={{ color: palette.white, fontSize: 9, fontWeight: 700 }}>✓</span>
          </div>
        )}
        <Body style={{ fontSize: 13, fontWeight: 600, color, margin: 0 } as React.CSSProperties}>
          {label}
        </Body>
      </div>
      <Body style={{ fontSize: 11, color: palette.gray.dark1, lineHeight: 1.5, maxWidth: 180 } as React.CSSProperties}>
        {desc}
      </Body>
    </div>
  )
}

// ─── Step illustrations ───────────────────────────────────────────────────────

function StepIllustration1() {
  return (
    <div style={{ padding: '28px 32px', display: 'flex', flexDirection: 'column', gap: 8 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: palette.gray.dark1, marginBottom: 4, fontFamily: 'inherit' }}>
        Package Name
      </div>
      <div style={{
        border: `2px solid ${palette.green.dark1}`, borderRadius: 6, padding: '10px 14px',
        background: palette.white, fontSize: 13, color: palette.black,
        fontFamily: "'Euclid Circular A', sans-serif",
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <span>AI Native Developer Campaign — Q2 2026</span>
        <div style={{ width: 2, height: 16, background: palette.green.dark1, animation: 'none' }} />
      </div>
      <div style={{ fontSize: 11, color: palette.gray.dark1, fontFamily: 'inherit' }}>
        e.g. Atlas Search Launch · Q3 2026
      </div>
    </div>
  )
}

function StepIllustration2() {
  return (
    <div style={{ padding: '20px 24px', display: 'flex', flexDirection: 'column', gap: 14 }}>
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: palette.gray.dark1, marginBottom: 6, fontFamily: 'inherit' }}>Prompt</div>
        <div style={{
          border: `1.5px solid ${palette.green.dark1}`, borderRadius: 6,
          padding: '10px 12px', background: palette.white,
          fontSize: 11, color: palette.black,
          fontFamily: "'Euclid Circular A', sans-serif", lineHeight: 1.55,
        }}>
          Write a blog post about production RAG pipelines using Atlas Vector Search, emphasizing operational simplicity and real-world lessons…
        </div>
      </div>
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: palette.gray.dark1, marginBottom: 6, fontFamily: 'inherit' }}>Attached files</div>
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' as const }}>
          <div style={{
            padding: '5px 10px', borderRadius: 5,
            border: `1px solid ${palette.gray.light2}`,
            background: palette.gray.light3,
            fontSize: 10, color: palette.gray.dark1, fontFamily: 'inherit',
          }}>
            product-brief.pdf
          </div>
          <div style={{
            padding: '5px 10px', borderRadius: 5,
            border: `1px solid ${palette.gray.light2}`,
            background: palette.white,
            fontSize: 10, color: palette.gray.dark1, fontFamily: 'inherit',
          }}>
            + Attach files
          </div>
        </div>
      </div>
    </div>
  )
}

function StepIllustration3() {
  return (
    <div style={{ display: 'flex', height: 160 }}>
      {/* Left form panel */}
      <div style={{ width: 140, borderRight: `1px solid ${palette.gray.light2}`, padding: '14px 12px', flexShrink: 0 }}>
        <div style={{ marginBottom: 10 }}>
          <div style={{ fontSize: 10, fontWeight: 600, color: palette.gray.dark1, marginBottom: 3, fontFamily: 'inherit' }}>Package Name</div>
          <div style={{ height: 8, borderRadius: 4, background: palette.gray.light2, width: '90%' }} />
        </div>
        <div style={{ marginBottom: 10 }}>
          <div style={{ fontSize: 10, fontWeight: 600, color: palette.gray.dark1, marginBottom: 3, fontFamily: 'inherit' }}>Prompt</div>
          <div style={{ height: 8, borderRadius: 4, background: palette.gray.light2, width: '80%', marginBottom: 4 }} />
          <div style={{ height: 8, borderRadius: 4, background: palette.gray.light2, width: '65%' }} />
        </div>
        {/* Locked fields shown faded */}
        {['Target Audience', 'Tone & Voice'].map(label => (
          <div key={label} style={{ marginBottom: 8, opacity: 0.35 }}>
            <div style={{ fontSize: 10, fontWeight: 600, color: palette.gray.dark1, marginBottom: 3, fontFamily: 'inherit' }}>{label}</div>
            <div style={{ height: 7, borderRadius: 4, background: palette.gray.light2, width: '70%' }} />
          </div>
        ))}
      </div>
      {/* Right preview panel */}
      <div style={{ flex: 1, padding: '14px 16px', background: palette.gray.light3 }}>
        <div style={{ display: 'flex', gap: 6, marginBottom: 10 }}>
          <div style={{ padding: '2px 8px', borderRadius: 4, background: palette.gray.light2, fontSize: 10, color: palette.gray.dark1, fontFamily: 'inherit' }}>Live Preview</div>
        </div>
        <div style={{ fontSize: 11, color: palette.black, lineHeight: 1.55, marginBottom: 10, fontFamily: "'Euclid Circular A', sans-serif" }}>
          "When we started building our RAG pipeline at scale, the first thing we broke…"
        </div>
        {[80, 65, 75, 55].map((w, i) => (
          <div key={i} style={{ height: 7, borderRadius: 3, background: palette.gray.light2, width: `${w}%`, marginBottom: 5 }} />
        ))}
      </div>
    </div>
  )
}

function StepIllustration4() {
  return (
    <div style={{ padding: '24px 32px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
        <div style={{ padding: '3px 10px', borderRadius: 4, background: palette.green.light3, border: `1px solid ${palette.green.dark1}`, fontSize: 11, fontWeight: 600, color: palette.green.dark2, fontFamily: 'inherit' }}>
          In Review
        </div>
        <span style={{ fontSize: 11, color: palette.gray.dark1, fontFamily: 'inherit' }}>AI Native Developer Campaign</span>
      </div>
      <div style={{ fontSize: 11, color: palette.gray.dark1, marginBottom: 12, fontFamily: 'inherit', lineHeight: 1.55 }}>
        Marked for review on Jun 10, 2026. Awaiting reviewer decision.
      </div>
      {[80, 65, 72].map((w, i) => (
        <div key={i} style={{ height: 7, borderRadius: 3, background: palette.gray.light2, width: `${w}%`, marginBottom: 6 }} />
      ))}
    </div>
  )
}

function StepIllustration5() {
  return (
    <div style={{ padding: '20px 24px' }}>
      <div style={{ fontSize: 12, color: palette.black, lineHeight: 1.6, marginBottom: 14, fontFamily: "'Euclid Circular A', sans-serif" }}>
        Building Production RAG: What We Got Wrong (And How to Fix It)
      </div>
      {[90, 75, 82, 60].map((w, i) => (
        <div key={i} style={{ height: 7, borderRadius: 3, background: palette.gray.light2, width: `${w}%`, marginBottom: 5 }} />
      ))}
      <div style={{
        marginTop: 14, paddingTop: 12, borderTop: `1px solid ${palette.gray.light2}`,
        display: 'flex', gap: 8,
      }}>
        <div style={{ padding: '6px 14px', borderRadius: 5, border: `1px solid ${palette.gray.light2}`, fontSize: 11, color: palette.gray.dark1, fontFamily: 'inherit' }}>Download for Review</div>
        <div style={{ padding: '6px 14px', borderRadius: 5, background: palette.green.dark2, fontSize: 11, color: palette.white, fontWeight: 600, fontFamily: 'inherit' }}>Mark for Review</div>
      </div>
    </div>
  )
}

function StepIllustrationRecord() {
  return (
    <div style={{ padding: '20px 24px' }}>
      {/* Package header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: palette.black, fontFamily: 'inherit' }}>
          AI Native Developer Campaign
        </div>
        <div style={{ padding: '2px 8px', borderRadius: 4, background: '#FEF3C7', border: '1px solid #FCD34D', fontSize: 10, fontWeight: 600, color: '#92400E', fontFamily: 'inherit' }}>
          In Review
        </div>
      </div>
      {/* Record decision card */}
      <div style={{ background: palette.white, border: `1px solid ${palette.gray.light2}`, borderRadius: 8, padding: '14px 16px' }}>
        <div style={{ fontSize: 10, fontWeight: 600, color: palette.gray.dark1, letterSpacing: '0.5px', marginBottom: 8, fontFamily: 'inherit' }}>
          RECORD DECISION
        </div>
        <div style={{ fontSize: 11, color: palette.gray.dark1, marginBottom: 14, fontFamily: 'inherit', lineHeight: 1.55 }}>
          Once you've received a decision from your reviewer, record it below.
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <div style={{ padding: '6px 12px', borderRadius: 5, background: palette.green.dark2, fontSize: 11, color: palette.white, fontWeight: 600, fontFamily: 'inherit' }}>
            Mark as Approved
          </div>
          <div style={{ padding: '6px 12px', borderRadius: 5, background: '#DC2626', fontSize: 11, color: palette.white, fontWeight: 600, fontFamily: 'inherit' }}>
            Mark as Denied
          </div>
        </div>
      </div>
    </div>
  )
}
