import { useState } from 'react'
import { Button } from '@leafygreen-ui/button'
import { Badge } from '@leafygreen-ui/badge'
import { Card } from '@leafygreen-ui/card'
// @ts-ignore
import { Stepper, Step } from '@leafygreen-ui/stepper'
import { H2, H3, Body, Overline } from '@leafygreen-ui/typography'
import Banner from '@leafygreen-ui/banner'
import { TextArea } from '@leafygreen-ui/text-area'
import { palette } from '../tokens'

// ─── Types ────────────────────────────────────────────────────────────────────

type PkgStatus = 'approved' | 'in-review' | 'denied'

interface Package {
  id: string
  name: string
  status: PkgStatus
  audience: string
  formats: string[]
  submittedDate: string
  hasVisual: boolean
  denialReason?: string
}

// ─── Mock data ────────────────────────────────────────────────────────────────

const PACKAGES: Package[] = [
  {
    id: 'agentic-apps',
    name: 'Agentic Apps Campaign — Q2 2026',
    status: 'in-review',
    audience: 'AI-Native Engineers',
    formats: ['Blog Post', 'LinkedIn Thread'],
    submittedDate: 'Jun 8, 2026',
    hasVisual: true,
  },
  {
    id: 'atlas-vector',
    name: 'Atlas Vector Search — Dev Guide',
    status: 'in-review',
    audience: 'Developer (General)',
    formats: ['Blog Post', 'Email Sequence'],
    submittedDate: 'Jun 9, 2026',
    hasVisual: false,
  },
  {
    id: 'mdb-ai',
    name: 'MongoDB AI Integration Playbook',
    status: 'approved',
    audience: 'Developer (General)',
    formats: ['Blog Post'],
    submittedDate: 'May 29, 2026',
    hasVisual: false,
  },
  {
    id: 'rag-tutorial',
    name: 'RAG Tutorial Series',
    status: 'denied',
    audience: 'AI-Native Engineers',
    formats: ['Blog Post', 'LinkedIn Thread'],
    submittedDate: 'May 22, 2026',
    hasVisual: false,
    denialReason: 'The content contained product capability claims that are not yet publicly available and cannot be published in customer-facing materials at this time. The overall framing also conflicts with current campaign messaging priorities. This package cannot be revised — please start a new package that accurately reflects current MongoDB capabilities.',
  },
]

const REVIEW_STEPS = ['Draft Created', 'Submitted', 'In Review', 'Completed']

const STEP_DESCRIPTIONS: Record<string, string> = {
  'Draft Created': 'Package configured and draft content generated by Ghostwriter.',
  'Submitted': 'Package submitted to the human review queue.',
  'In Review': 'A MongoDB content reviewer is examining your drafts for accuracy and brand alignment.',
  'Completed': 'Review process complete. See status above for the outcome.',
}

const DRAFT_EXCERPT = `Your agent is not broken. Your memory evaluation process is.

You shipped an agent that looked strong in internal demos, then production behavior drifted. It forgets key user preferences in one flow, resurrects stale context in another, and occasionally pulls irrelevant history into critical decisions.

Teams usually react by swapping vector stores, tweaking chunking strategies, or rewriting prompts. Weeks later, quality is still unstable.

This is the real failure mode: there's no shared framework for evaluating memory systems under production constraints.

THE THREE METRICS THAT ACTUALLY MATTER

1. Precision — Does retrieved context belong in this response?
Most teams optimize for recall alone. High recall with low precision means your agent is retrieving technically relevant context that's wrong for the current moment.

2. Recall — Is the right context available when needed?
The underrated metric. Gaps in recall don't show up in benchmarks. They surface when a user references a preference from three conversations ago and the agent draws a blank.

3. Cost per query — What does "good memory" cost at production scale?
A rubric that ignores cost creates brittle systems. The right memory architecture for 10 users per day is usually wrong for 10,000.

The teams that ship reliable agent memory don't have better infrastructure. They have better evaluation.`

const STATUS_META: Record<PkgStatus, { label: string; badgeVariant: 'green' | 'blue' | 'red' | 'yellow'; bannerVariant: 'success' | 'info' | 'danger' | 'warning'; stepIdx: number }> = {
  'approved':  { label: 'Approved',  badgeVariant: 'green',  bannerVariant: 'success', stepIdx: 3 },
  'in-review': { label: 'In Review', badgeVariant: 'yellow', bannerVariant: 'warning', stepIdx: 2 },
  'denied':    { label: 'Denied',    badgeVariant: 'red',    bannerVariant: 'danger',  stepIdx: 3 },
}

const BANNER_MESSAGES: Record<PkgStatus, string> = {
  'approved':  'Your package has been approved and is ready to distribute.',
  'in-review': 'Your package is currently being reviewed. You\'ll be notified when the review is complete.',
  'denied':    'Your package was denied. Review the reason below and start a new package with a revised approach.',
}

// ─── PackageHistoryV4 ─────────────────────────────────────────────────────────

export function PackageHistoryV4({ onBack }: { onBack: () => void }) {
  const [selectedId, setSelectedId]     = useState('agentic-apps')
  const [packages, setPackages]         = useState<Package[]>(PACKAGES)
  const [denying, setDenying]           = useState(false)
  const [denialReason, setDenialReason] = useState('')

  const selected       = packages.find(p => p.id === selectedId)!
  const meta           = STATUS_META[selected.status]
  const currentStepIdx = meta.stepIdx

  const selectPackage = (id: string) => {
    setSelectedId(id)
    setDenying(false)
    setDenialReason('')
  }

  const handleApprove = () => {
    setPackages(prev => prev.map(p => p.id === selectedId ? { ...p, status: 'approved' as const } : p))
  }

  const handleDeny = (reason: string) => {
    setPackages(prev => prev.map(p => p.id === selectedId ? { ...p, status: 'denied' as const, denialReason: reason } : p))
    setDenying(false)
    setDenialReason('')
  }

  return (
    <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>

      {/* ── Sidebar ─────────────────────────────────────────────────────── */}
      <div style={{
        width: 288, flexShrink: 0, borderRight: `1px solid ${palette.gray.light2}`,
        overflowY: 'auto', background: palette.gray.light3,
        display: 'flex', flexDirection: 'column',
      }}>
        <div style={{
          padding: '20px 20px 12px', borderBottom: `1px solid ${palette.gray.light2}`,
          background: palette.white,
        }}>
          <Overline style={{ display: 'block', marginBottom: 4 }}>Package History</Overline>
          <Body style={{ fontSize: 12, color: palette.gray.dark1 } as React.CSSProperties}>
            {packages.length} packages
          </Body>
        </div>

        {packages.map(pkg => {
          const m = STATUS_META[pkg.status]
          const isSelected = pkg.id === selectedId
          return (
            <button
              key={pkg.id}
              onClick={() => selectPackage(pkg.id)}
              style={{
                display: 'block', width: '100%', textAlign: 'left',
                padding: '14px 20px', border: 'none', cursor: 'pointer',
                background: isSelected ? palette.white : 'transparent',
                borderLeft: isSelected ? `3px solid ${palette.green.dark1}` : '3px solid transparent',
                borderBottom: `1px solid ${palette.gray.light2}`,
                fontFamily: "'Euclid Circular A', sans-serif",
              }}
            >
              <div style={{ fontSize: 13, fontWeight: 600, color: palette.black, marginBottom: 6, lineHeight: 1.35 }}>
                {pkg.name}
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' as const }}>
                <Badge variant={m.badgeVariant}>{m.label}</Badge>
                <span style={{ fontSize: 11, color: palette.gray.base, fontFamily: 'inherit' }}>
                  {pkg.submittedDate}
                </span>
              </div>
            </button>
          )
        })}
      </div>

      {/* ── Detail panel ────────────────────────────────────────────────── */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '36px 40px 56px' }}>

        {/* Package header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 24 }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
              <H2 style={{ margin: 0 }}>{selected.name}</H2>
              <Badge variant={meta.badgeVariant}>{meta.label}</Badge>
            </div>
            <div style={{ display: 'flex', alignItems: 'stretch', gap: 0 }}>
              {[
                { label: 'Audience', value: selected.audience },
                { label: 'Formats', value: selected.formats.join(', ') },
                ...(selected.hasVisual ? [{ label: 'Visual Design', value: 'Included' }] : []),
              ].map((item, i, arr) => (
                <div key={item.label} style={{
                  display: 'flex', flexDirection: 'column' as const, gap: 3,
                  paddingRight: i < arr.length - 1 ? 20 : 0,
                  marginRight: i < arr.length - 1 ? 20 : 0,
                  borderRight: i < arr.length - 1 ? `1px solid ${palette.gray.light1}` : 'none',
                }}>
                  <Overline style={{ display: 'block', color: palette.gray.dark1, fontWeight: 700 } as React.CSSProperties}>{item.label}</Overline>
                  <Body style={{ color: palette.black, fontWeight: 500, margin: 0 } as React.CSSProperties}>{item.value}</Body>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Status banner */}
        <Banner variant={meta.bannerVariant} style={{ marginBottom: 28 }}>
          {BANNER_MESSAGES[selected.status]}
        </Banner>

        {/* Review progress */}
        <Card style={{ padding: '24px 28px', marginBottom: 28 }}>
          <Overline style={{ display: 'block', marginBottom: 20 }}>Review Progress</Overline>
          {/* @ts-ignore */}
          <Stepper currentStep={currentStepIdx}>
            {REVIEW_STEPS.map(label => (
              // @ts-ignore
              <Step key={label}>{label}</Step>
            ))}
          </Stepper>
          <div style={{
            display: 'grid', gridTemplateColumns: `repeat(${REVIEW_STEPS.length}, 1fr)`,
            gap: 8, marginTop: 16,
          }}>
            {REVIEW_STEPS.map((label, i) => (
              <div key={label}>
                <Body style={{ fontSize: 11, color: i <= currentStepIdx ? palette.black : palette.gray.base, textAlign: 'center' } as React.CSSProperties}>
                  {STEP_DESCRIPTIONS[label]}
                </Body>
              </div>
            ))}
          </div>
        </Card>

        {/* ── In Review ────────────────────────────────────────────────── */}
        {selected.status === 'in-review' && (
          <div>
            {!denying ? (
              <Card style={{ padding: '20px 24px' }}>
                <Overline style={{ display: 'block', marginBottom: 14, color: palette.gray.dark1 }}>RECORD DECISION</Overline>
                <Body style={{ color: palette.gray.dark1, marginBottom: 20 } as React.CSSProperties}>
                  Once you've received a decision from your external reviewer, record it below to update the package status.
                </Body>
                <div style={{ display: 'flex', gap: 12 }}>
                  <Button variant="primary" onClick={handleApprove}>Mark as Approved</Button>
                  <Button variant="danger" onClick={() => setDenying(true)}>Mark as Denied</Button>
                </div>
              </Card>
            ) : (
              <Card style={{ padding: '20px 24px' }}>
                <div style={{ marginBottom: 20 }}>
                  {/* @ts-ignore */}
                  <TextArea
                    label="Reason for Denial"
                    description="Enter the reason provided by your reviewer so you can reference it later."
                    value={denialReason}
                    onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setDenialReason(e.target.value)}
                    placeholder="e.g. Several product claims are not aligned with current documentation…"
                  />
                </div>
                <div style={{ display: 'flex', gap: 12 }}>
                  <Button
                    variant="danger"
                    disabled={!denialReason.trim()}
                    onClick={() => handleDeny(denialReason.trim())}
                  >
                    Confirm Denial
                  </Button>
                  <Button variant="default" onClick={() => { setDenying(false); setDenialReason('') }}>
                    Cancel
                  </Button>
                </div>
              </Card>
            )}
          </div>
        )}


        {/* ── Denied detail ────────────────────────────────────────────── */}
        {selected.status === 'denied' && (
          <div>
            {selected.denialReason && (
              <Card style={{ padding: '20px 24px', marginBottom: 24 }}>
                <Overline style={{ display: 'block', marginBottom: 8, color: palette.gray.dark1 }}>REASON FOR DENIAL</Overline>
                <Body style={{ color: palette.black, lineHeight: 1.7 }}>{selected.denialReason}</Body>
              </Card>
            )}
            <Button variant="primary" onClick={onBack}>Start a New Package →</Button>
          </div>
        )}
      </div>
    </div>
  )
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const draftPreStyle: React.CSSProperties = {
  color: palette.black, fontSize: 13, lineHeight: 1.85,
  fontFamily: "'Euclid Circular A', sans-serif",
  whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0,
}

